repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: \.(yml|yaml|py|sql|groovy|json)$|Dockerfile
      - id: end-of-file-fixer
        files: \.(yml|yaml|py|sql|groovy|json)$|Dockerfile
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: check-json
        files: \.json$
      - id: check-added-large-files
        files: \.(yml|yaml|py|sql|groovy|json)$|Dockerfile

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: \.py$
