---
version: '3'

x-test-service: &test_service
  networks:
    - backend-network
    - frontend-network
  command: [ "python3", "-m", "robot", "-d", "result/", "testcases/api_test.robot" ]

services:
  account_test:
    image: account_test:1.0
    container_name: account_test
    profiles:
      - allservice
      - account
    build:
      context: ./services/account/test
      dockerfile: Dockerfile
    volumes:
      - ./services/account/test/result:/test/result
    <<: *test_service

  inventory_test:
    image: inventory_test:1.0
    container_name: inventory_test
    profiles:
      - allservice
      - inventory
    build:
      context: ./services/inventory/test
      dockerfile: Dockerfile
    volumes:
      - ./services/inventory/test/result:/test/result
    <<: *test_service

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
