version: '3.8'

x-app-service: &app_service
  depends_on:
    data_feed:
      condition: service_completed_successfully
    rabbitmq:
      condition: service_healthy
  networks:
    - db-network
    - backend-network
  environment:
      TZ: Asia/Ho_Chi_Minh
      PYTHONUNBUFFERED: 1
  command: [ "python3", "app.py" ]
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
    interval: 30s
    timeout: 10s
    retries: 5

services:
  pg_db:
    image: postgres:${DB_VERSION}
    container_name: pg_db
    restart: always
    profiles:
      - system
      - db
    networks:
      - db-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgres/data
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    profiles:
      - system
      - event-bus
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./event_bus/lib:/var/lib/rabbitmq
      - ./event_bus/log:/var/log/rabbitmq
    networks:
      - backend-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  data_feed:
    image: data_feed
    build:
      context: ./tool/testdata
      dockerfile: Dockerfile
    container_name: data_feed
    profiles:
      - system
      - db
    depends_on:
      pg_db:
        condition: service_healthy
    networks:
      - db-network

  api_gateway:
    image: nginx:1.23.3
    container_name: api_gateway
    restart: unless-stopped
    profiles:
      - system
    depends_on:
      account:
        condition: service_healthy
      discount:
        condition: service_healthy
      order:
        condition: service_healthy
      inventory:
        condition: service_healthy
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - frontend-network
      - backend-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  account:
    image: account:${APP_TAG}
    build:
      context: ./services/account/src
      dockerfile: Dockerfile
    container_name: account
    profiles:
      - system
      - account
    <<: *app_service

  inventory:
    image: inventory:${APP_TAG}
    build:
      context: ./services/inventory/src
      dockerfile: Dockerfile
    container_name: inventory
    profiles:
      - system
      - inventory
    <<: *app_service

  order:
    image: order:${APP_TAG}
    build:
      context: ./services/order/src
      dockerfile: Dockerfile
    container_name: order
    profiles:
      - system
      - order
    <<: *app_service

  discount:
    image: discount:${APP_TAG}
    build:
      context: ./services/discount/src
      dockerfile: Dockerfile
    container_name: discount
    profiles:
      - system
      - discount
    <<: *app_service

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  db-network:
    driver: bridge
