version: '3.8'

x-app-service: &app_service
  depends_on:
    - pg_db
  networks:
    - db-network
    - backend-network
  command: [ "python3", "app.py" ]

services:
  pg_db:
    image: postgres:${DB_VERSION}
    container_name: pg_db
    restart: always
    profiles:
      - system
      - db
    ports:
      - ${DB_PORT}:5432
    networks:
      - db-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgres/data
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api_gateway:
    image: nginx:1.23.3
    container_name: api_gateway
    restart: unless-stopped
    profiles:
      - system
    depends_on:
      - account
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - frontend-network
      - backend-network

  account:
    image: account:${APP_TAG}
    build:
      context: ./services/account/src
      dockerfile: Dockerfile
    container_name: account
    profiles:
      - system
      - account
    volumes:
      - ./services/account/src:/app
    <<: *app_service

  order:
    image: order:${APP_TAG}
    build:
      context: ./services/order/src
      dockerfile: Dockerfile
    container_name: order
    profiles:
      - system
      - order
    volumes:
      - ./services/order/src:/app
    <<: *app_service

  authorize:
    image: authorize:${APP_TAG}
    build:
      context: ./services/authorize/src
      dockerfile: Dockerfile
    container_name: authorize
    profiles:
      - system
      - authorize
    volumes:
      - ./services/authorize/src:/app
    <<: *app_service

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  db-network:
    driver: bridge
